version: '3.8'
services:
  greetings-app-dev:
    build: .
    image: romansasacovs/python-greetings-app:latest
    container_name: greetings-app-dev
    ports: 
      - 7001:3000
  greetings-app-stg:
    build: .
    image: romansasacovs/python-greetings-app:latest
    container_name: greetings-app-stg
    ports: 
      - 7002:3000
  greetings-app-prod:
    build: .
    image: romansasacovs/python-greetings-app:latest
    container_name: greetings-app-prod
    ports: 
      - 7003:3000